### ISSUE TITLE
[OTHER]How should the APP handle the person's ID ?

### ISSUE THREAD

**Issue by lduf** [TC-netw4ppl/android-app#111]
**1st option**
To simplify the server integration process, the application must generate a UUID for each person created.

The probability of duplication is low and this makes it easier to create relationships within the application and also makes it easier for the server to find them.

**2nd option**

The application generates any internal id and manages it as it wishes. When it pushes the data to the server, it starts with push person. The server responds by giving an id for each person. The application uses the ids generated by the server to chat with the server.

**Comment by lduf** [comment]
2nd option possibilities : 

store a transcription file to match local IDs with distant IDs

**Comment by mathisfchx** [comment]
#133 is solving with 1st option (issue #122)
